# This is a basic workflow to help you get started with Actions

name: lint
on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      HUSKY: 0
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: install
        run: npm ci
      - name: Lint
        run: |
          git config --global user.email "tos.oliveira2@gmail.com"
          git config --global user.name "codibrebot"
          npm run lint:fix
          git add .
          git commit -m 'refactor: fixing lint'
          git push origin HEAD
