name: semantic-release

on:
  push:
    branches: [master]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npm run build --if-present
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
      - run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npx semantic-release
      - run: npm publish
